const mockArticles: Article[] = [
  {
    id: 1,
    binCode: 'BIN-OFF-001',
    name: 'A4 Office Paper',
    description: 'Office Paper A4 - 80gsm',
    category: 'office-supplies',
    type: 'consumable',
    unit: 'sheets',
    cost: 0.02,
    supplier: 'Office Supplies Inc.',
    currentStock: 2500,
    minStock: 500,
    location: 'Storage Room A',
    status: 'good-condition',
    imageUrl: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=300',
    createdAt: '2025-01-15'
  },
  {
    id: 2,
    binCode: 'BIN-TECH-002',
    name: 'Dell Latitude Laptop',
    description: 'Laptop Dell Latitude 5520',
    category: 'technology',
    type: 'non-consumable',
    unit: 'units',
    cost: 1200,
    supplier: 'Tech Solutions Ltd.',
    currentStock: 15,
    minStock: 5,
    location: 'IT Storage',
    status: 'good-condition',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300',
    createdAt: '2025-01-14'
  },
  {
    id: 3,
    binCode: 'BIN-USB-003',
    name: 'USB Type-C Cable',
    description: 'USB Cable Type-C 2m',
    category: 'technology',
    type: 'consumable',
    unit: 'units',
    cost: 15,
    supplier: 'Cable Corp.',
    currentStock: 50,
    minStock: 20,
    location: 'IT Storage',
    status: 'good-condition',
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=300',
    createdAt: '2025-01-13'
  },
  {
    id: 4,
    binCode: 'BIN-TOOL-004',
    name: 'Electric Drill',
    description: 'Electric Drill with Battery',
    category: 'tools',
    type: 'non-consumable',
    unit: 'units',
    cost: 250,
    supplier: 'Tool Masters',
    currentStock: 8,
    minStock: 3,
    location: 'Workshop',
    status: 'good-condition',
    imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=300',
    createdAt: '2025-01-12'
  },
  {
    id: 5,
    binCode: 'BIN-SAFE-005',
    name: 'Safety Helmet',
    description: 'Safety Helmet with Chin Strap',
    category: 'safety-equipment',
    type: 'non-consumable',
    unit: 'units',
    cost: 45,
    supplier: 'SafetyFirst Co.',
    currentStock: 25,
    minStock: 10,
    location: 'Safety Storage',
    status: 'good-condition',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300',
    createdAt: '2025-01-11'
  }
];